server:
  port: 8085

spring:
  application:
    name: post-service
  datasource:
    url: jdbc:postgresql://localhost:5432/socialdatabase
    username: social
    password: social123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect